### DS210 Final - Data Cleaning
I used Python (and more specifically, the pandas package) to clean the data for my final project on Boston Marathon degrees of separation because of the number of CSV files used for the project and for my own clarity.

In [1]:
import pandas as pd
import country_converter as coco

##### Winners, from https://www.kaggle.com/datasets/zhikchen/boston-marathon-winners-men-and-women

In [2]:
winners_w = pd.read_csv('Womens_Boston_Marathon_Winners.csv')
winners_m = pd.read_csv('Mens_Boston_Marathon_Winners.csv')

print(len(winners_w))
print(len(winners_m))

57
126

In [3]:
win_df = [winners_w,winners_m]
winners = pd.concat(win_df)
winners = winners.reset_index()

# deleting nan for 1918, 2022 (no marathon)
winners = winners.drop([winners.index[78],winners.index[180],winners.index[54]])

winners

,index,Year,Winner,Country,Time,Distance (Miles),Distance (KM)
0,0,1966.0,Bobbi Gibb,United States,3:21:40,26.2,42.2
1,1,1967.0,Bobbi Gibb,United States,3:27:17,26.2,42.2
2,2,1968.0,Bobbi Gibb,United States,3:30:00,26.2,42.2
3,3,1969.0,Sara Mae Berman,United States,3:22:46,26.2,42.2
4,4,1970.0,Sara Mae Berman,United States,3:05:07,26.2,42.2
...,...,...,...,...,...,...,...
177,120,2017.0,Geoffrey Kirui,Kenya,02:09:37,26.2,42.2
178,121,2018.0,Yuki Kawauchi,Japan,02:15:58,26.2,42.2
179,122,2019.0,Lawrence Cherono,Kenya,02:07:57,26.2,42.2
181,124,2021.0,Benson Kipruto,Kenya,02:09:51,26.2,42.2
182,125,2022.0,Evans Chebet,Kenya,02:06:51,26.2,42.2

In [4]:
win_countries = list(winners.Country.unique())
win_countries

['United States',
 'Germany',
 'Canada',
 'New Zealand',
 'Norway',
 'Portugal',
 'Poland',
 'Russia',
 'Ethiopia',
 'Kenya',
 'Greece',
 'South Korea',
 'Sweden',
 'Japan',
 'Guatemala',
 'Finland',
 'Yugoslavia',
 'Belgium',
 'United Kingdom',
 'Colombia',
 'Ireland',
 'Australia',
 'Italy']

##### Finishers from 2015-2017, from https://www.kaggle.com/datasets/rojour/boston-results?select=marathon_results_2017.csv

In [5]:
mar_2015 = pd.read_csv('marathon_results_2015.csv')
mar_2016 = pd.read_csv('marathon_results_2016.csv')
mar_2017 = pd.read_csv('marathon_results_2017.csv')

In [6]:
mar_2015['Year'] = 2015
mar_2016['Year'] = 2016
mar_2017['Year'] = 2017

In [7]:
other_df = [mar_2015, mar_2016, mar_2017]
other = pd.concat(other_df)
other

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Year,Unnamed: 8
0,0.0,3,"Desisa, Lelisa",25,M,Ambo,NaN,ETH,NaN,NaN,...,1:47:59,2:02:39,0:04:56,-,2:09:17,1,1,1,2015,NaN
1,1.0,4,"Tsegay, Yemane Adhane",30,M,Addis Ababa,NaN,ETH,NaN,NaN,...,1:47:59,2:02:42,0:04:58,-,2:09:48,2,2,2,2015,NaN
2,2.0,8,"Chebet, Wilson",29,M,Marakwet,NaN,KEN,NaN,NaN,...,1:47:59,2:03:01,0:04:59,-,2:10:22,3,3,3,2015,NaN
3,3.0,11,"Kipyego, Bernard",28,M,Eldoret,NaN,KEN,NaN,NaN,...,1:48:03,2:03:47,0:05:00,-,2:10:47,4,4,4,2015,NaN
4,4.0,10,"Korir, Wesley",32,M,Kitale,NaN,KEN,NaN,NaN,...,1:47:59,2:03:27,0:05:00,-,2:10:49,5,5,5,2015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26405,26405.0,25166,"Steinbach, Paula Eyvonne",61,F,Ontario,CA,USA,NaN,MI,...,5:55:18,6:46:57,0:16:24,-,7:09:39,26407,11972,344,2017,NaN
26406,26406.0,25178,"Avelino, Andrew R.",25,M,Fayetteville,NC,USA,NaN,MI,...,5:53:48,6:54:21,0:16:40,-,7:16:59,26408,14436,4774,2017,NaN
26407,26407.0,27086,"Hantel, Johanna",57,F,Malvern,PA,USA,NaN,NaN,...,6:00:33,6:54:38,0:16:47,-,7:19:37,26409,11973,698,2017,NaN
26408,26408.0,25268,"Reilly, Bill",64,M,New York,NY,USA,NaN,MI,...,6:06:07,6:56:08,0:16:49,-,7:20:44,26410,14437,1043,2017,NaN
26409,26409.0,25266,"Rigsby, Scott",48,M,Alpharetta,GA,USA,NaN,MI,...,6:39:07,7:41:23,0:18:15,-,7:58:14,26411,14438,2553,2017,NaN

In [8]:
other.Country.unique()

array(['ETH', 'KEN', 'USA', 'UKR', 'RSA', 'ITA', 'RUS', 'JPN', 'CAN',
       'BEL', 'NZL', 'BLR', 'AUS', 'GBR', 'CRO', 'ECU', 'GER', 'ESP',
       'SWE', 'BRA', 'HKG', 'MEX', 'DEN', 'MAS', 'IRL', 'ISL', 'CHI',
       'GUA', 'FIN', 'SVK', 'COL', 'SUI', 'CHN', 'AUT', 'NED', 'FRA',
       'CRC', 'CYP', 'POL', 'NOR', 'KOR', 'POR', 'TPE', 'PER', 'SIN',
       'PAN', 'VEN', 'LUX', 'CZE', 'VIE', 'MAR', 'BER', 'ROU', 'IND',
       'LIE', 'ARG', 'ESA', 'DOM', 'ISR', 'GRE', 'SLO', 'LTU', 'URU',
       'CAY', 'EST', 'JAM', 'UAE', 'VGB', 'TUR', 'LAT', 'AND', 'OMA',
       'BAH', 'TRI', 'INA', 'AHO', 'PHI', 'UGA', 'QAT', 'ZIM', 'TWN',
       'HON', 'FLK', 'HUN', 'JOR', 'ALB', 'SRB', 'PAK', 'BRN', 'BDI',
       'EGY', 'THA', 'MLT', 'KSA', 'SMR', 'BUL', 'ALG', 'NCA', 'BAR',
       'GRN', 'PAR', 'TCA', 'KUW', 'MGL', 'NGR'], dtype=object)

In [9]:
# create a list of the countries as given
false_iso3_list = []
for country in other.Country:
    false_iso3_list.append(country)

In [10]:
# unfortunately the boston marathon registration site (where the data was sourced originally) simply does not use io3 designation
# the following code fixes that to properly use the country_converter package
# checked against the marathon cite and https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
iso3_list = []
for country in false_iso3_list:
    if country=='RSA':
        new_c = 'RUS'
    elif country=='CRO':
        new_c = 'HRV'
    elif country=='GER':
        new_c = 'DEU'
    elif country=='DEN':
        new_c = 'DNK'
    elif country=='MAS':
        new_c = 'MYS'
    elif country=='CHI':
        new_c = 'CHN'
    elif country=='GUA':
        new_c = 'GTM'
    elif country=='SUI':
        new_c = 'CHE'
    elif country=='NED':
        new_c = 'NLD'
    elif country=='CRC':
        new_c = 'CRI'
    elif country=='POR':
        new_c = 'PRT'
    elif country=='TPE': # TWN in 2016, 2017; only different in 2015
        new_c = 'TWN'
    elif country=='SIN':
        new_c = 'SGP'
    elif country=='BER':
        new_c = 'BMU'
    elif country=='VIE':
        new_c = 'VNM'
    elif country=='ESA':
        new_c = 'SLV'
    elif country=='GRE':
        new_c = 'GRL'
    elif country=='SLO':
        new_c = 'SVN'
    elif country=='URU':
        new_c = 'URY'
    elif country=='CAY':
        new_c = 'CYM'
    elif country=='UAE':
        new_c = 'ARE'
    elif country=='TRI':
        new_c = 'TTO'
    elif country=='INA':
        new_c = 'IDN'
    elif country=='AHO':
        new_c = 'CUW'
    elif country=='PHI':
        new_c = 'PHL'
    elif country=='ZIM':
        new_c = 'ZWE'
    elif country=='HON':
        new_c = 'HND'
    elif country=='LAT':
        new_c = 'LVA'
    elif country=='OMA':
        new_c = 'OMN'
    elif country=='BAH':
        new_c = 'BHS'
    elif country=='KSA':
        new_c = 'SAU'
    elif country=='BUL':
        new_c = 'BGR'
    elif country=='ALG':
        new_c = 'DZA'
    elif country=='NCA':
        new_c = 'NIC'
    elif country=='BAR':
        new_c = 'BRB'
    elif country=='NGR':
        new_c = 'NGA'
    elif country=='GRN':
        new_c = 'GRL'
    elif country=='MGL':
        new_c = 'MNG'
    elif country=='PAR':
        new_c = 'PRY'
    elif country=='KUW':
        new_c = 'KWT'
    else:
        new_c = country
    iso3_list.append(new_c)

In [11]:
iso3_list

['ETH',
 'ETH',
 'KEN',
 'KEN',
 'KEN',
 'KEN',
 'USA',
 'USA',
 'ETH',
 'UKR',
 'USA',
 'USA',
 'RUS',
 'USA',
 'ITA',
 'USA',
 'RUS',
 'USA',
 'USA',
 'USA',
 'JPN',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'ITA',
 'KEN',
 'ETH',
 'USA',
 'ETH',
 'CAN',
 'JPN',
 'USA',
 'USA',
 'USA',
 'USA',
 'JPN',
 'USA',
 'USA',
 'KEN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'KEN',
 'USA',
 'ETH',
 'USA',
 'USA',
 'BEL',
 'ETH',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'NZL',
 'USA',
 'USA',
 'USA',
 'USA',
 'KEN',
 'CAN',
 'USA',
 'BLR',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'AUS',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'GBR',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'HRV',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'ECU',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'GBR',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'DEU',
 'ESP',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'SWE',
 'USA',
 'ESP',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'BRA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'HKG',
 'USA',
 'USA',
 'USA',
 'JPN',
 'USA',
 'USA',
 'CAN',
 'USA',
 'MEX',
 'BEL',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'SWE',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'DEU',
 'USA',
 'DEU',
 'USA',
 'USA',
 'DNK',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'NZL',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'ESP',
 'CAN',
 'HRV',
 'USA',
 'MEX',
 'USA',
 'USA',
 'MYS',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'IRL',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'JPN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'ISL',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'ESP',
 'CAN',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'CHN',
 'GTM',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'MEX',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'AUS',
 'USA',
 'FIN',
 'USA',
 'DEU',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'GBR',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'SVK',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CHN',
 'CAN',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'MEX',
 'USA',
 'ITA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'AUS',
 'USA',
 'JPN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'MEX',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'JPN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'COL',
 'USA',
 'USA',
 'USA',
 'DEU',
 'CHE',
 'MEX',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'IRL',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'GBR',
 'USA',
 'USA',
 'USA',
 'JPN',
 'COL',
 'USA',
 'USA',
 'USA',
 'RUS',
 'USA',
 'CAN',
 'USA',
 'CHN',
 'USA',
 'AUT',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'GBR',
 'USA',
 'MEX',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'JPN',
 'USA',
 'ITA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'GBR',
 'SVK',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'NLD',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CHN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'JPN',
 'USA',
 'AUS',
 'USA',
 'CAN',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'GBR',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'CHE',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'IRL',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'ESP',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'AUS',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'MEX',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'ITA',
 'AUS',
 'USA',
 'USA',
 'USA',
 'CHE',
 'USA',
 'USA',
 'USA',
 'MEX',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'MEX',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'KEN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'FRA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'SWE',
 'USA',
 'USA',
 'USA',
 'USA',
 'RUS',
 'USA',
 'DEU',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'GBR',
 'USA',
 'USA',
 'USA',
 'GTM',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'USA',
 'USA',
 'ITA',
 'USA',
 'ECU',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'CAN',
 'USA',
 'USA',
 'CRI',
 'USA',
 'USA',
 'CAN',
 'USA',
 'CYP',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'AUS',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'USA',
 'FIN',
 'USA',
 ...]

In [12]:
countries = coco.convert(names=iso3_list, to='name_official')
countries

['Federal Democratic Republic of Ethiopia',
 'Federal Democratic Republic of Ethiopia',
 'Republic of Kenya',
 'Republic of Kenya',
 'Republic of Kenya',
 'Republic of Kenya',
 'United States of America',
 'United States of America',
 'Federal Democratic Republic of Ethiopia',
 'Ukraine',
 'United States of America',
 'United States of America',
 'Russian Federation',
 'United States of America',
 'Italian Republic',
 'United States of America',
 'Russian Federation',
 'United States of America',
 'United States of America',
 'United States of America',
 'Japan',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'Italian Republic',
 'Republic of Kenya',
 'Federal Democratic Republic of Ethiopia',
 'United States of America',
 'Federal Democratic Republic of Ethiopia',
 'Canada',
 'Japan',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Japan',
 'United States of America',
 'United States of America',
 'Republic of Kenya',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Republic of Kenya',
 'United States of America',
 'Federal Democratic Republic of Ethiopia',
 'United States of America',
 'United States of America',
 'Kingdom of Belgium',
 'Federal Democratic Republic of Ethiopia',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'New Zealand',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Republic of Kenya',
 'Canada',
 'United States of America',
 'Republic of Belarus',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Commonwealth of Australia',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'Republic of Croatia',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Republic of Ecuador',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Federal Republic of Germany',
 'Kingdom of Spain',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Kingdom of Sweden',
 'United States of America',
 'Kingdom of Spain',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Federative Republic of Brazil',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Hong Kong SAR',
 'United States of America',
 'United States of America',
 'United States of America',
 'Japan',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United Mexican States',
 'Kingdom of Belgium',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Kingdom of Sweden',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'Federal Republic of Germany',
 'United States of America',
 'Federal Republic of Germany',
 'United States of America',
 'United States of America',
 'Kingdom of Denmark',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'New Zealand',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Kingdom of Spain',
 'Canada',
 'Republic of Croatia',
 'United States of America',
 'United Mexican States',
 'United States of America',
 'United States of America',
 'Malaysia',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'Ireland',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Japan',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Republic of Iceland',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Kingdom of Spain',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 "People's Republic of China",
 'Republic of Guatemala',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United Mexican States',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Commonwealth of Australia',
 'United States of America',
 'Republic of Finland',
 'United States of America',
 'Federal Republic of Germany',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Slovak Republic',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 "People's Republic of China",
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United Mexican States',
 'United States of America',
 'Italian Republic',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Commonwealth of Australia',
 'United States of America',
 'Japan',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United Mexican States',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'Japan',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Republic of Colombia',
 'United States of America',
 'United States of America',
 'United States of America',
 'Federal Republic of Germany',
 'Swiss Confederation',
 'United Mexican States',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'Ireland',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'United States of America',
 'United States of America',
 'Japan',
 'Republic of Colombia',
 'United States of America',
 'United States of America',
 'United States of America',
 'Russian Federation',
 'United States of America',
 'Canada',
 'United States of America',
 "People's Republic of China",
 'United States of America',
 'Republic of Austria',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
 'United States of America',
 'United Mexican States',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Japan',
 'United States of America',
 'Italian Republic',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'United States of America',
 'Canada',

In [13]:
other['Country'] = countries
other

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Year,Unnamed: 8
0,0.0,3,"Desisa, Lelisa",25,M,Ambo,NaN,Federal Democratic Republic of Ethiopia,NaN,NaN,...,1:47:59,2:02:39,0:04:56,-,2:09:17,1,1,1,2015,NaN
1,1.0,4,"Tsegay, Yemane Adhane",30,M,Addis Ababa,NaN,Federal Democratic Republic of Ethiopia,NaN,NaN,...,1:47:59,2:02:42,0:04:58,-,2:09:48,2,2,2,2015,NaN
2,2.0,8,"Chebet, Wilson",29,M,Marakwet,NaN,Republic of Kenya,NaN,NaN,...,1:47:59,2:03:01,0:04:59,-,2:10:22,3,3,3,2015,NaN
3,3.0,11,"Kipyego, Bernard",28,M,Eldoret,NaN,Republic of Kenya,NaN,NaN,...,1:48:03,2:03:47,0:05:00,-,2:10:47,4,4,4,2015,NaN
4,4.0,10,"Korir, Wesley",32,M,Kitale,NaN,Republic of Kenya,NaN,NaN,...,1:47:59,2:03:27,0:05:00,-,2:10:49,5,5,5,2015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26405,26405.0,25166,"Steinbach, Paula Eyvonne",61,F,Ontario,CA,United States of America,NaN,MI,...,5:55:18,6:46:57,0:16:24,-,7:09:39,26407,11972,344,2017,NaN
26406,26406.0,25178,"Avelino, Andrew R.",25,M,Fayetteville,NC,United States of America,NaN,MI,...,5:53:48,6:54:21,0:16:40,-,7:16:59,26408,14436,4774,2017,NaN
26407,26407.0,27086,"Hantel, Johanna",57,F,Malvern,PA,United States of America,NaN,NaN,...,6:00:33,6:54:38,0:16:47,-,7:19:37,26409,11973,698,2017,NaN
26408,26408.0,25268,"Reilly, Bill",64,M,New York,NY,United States of America,NaN,MI,...,6:06:07,6:56:08,0:16:49,-,7:20:44,26410,14437,1043,2017,NaN
26409,26409.0,25266,"Rigsby, Scott",48,M,Alpharetta,GA,United States of America,NaN,MI,...,6:39:07,7:41:23,0:18:15,-,7:58:14,26411,14438,2553,2017,NaN

##### Beginning the Combination Process

In [14]:
win_countries
## unique countries that have had winners

['United States',
 'Germany',
 'Canada',
 'New Zealand',
 'Norway',
 'Portugal',
 'Poland',
 'Russia',
 'Ethiopia',
 'Kenya',
 'Greece',
 'South Korea',
 'Sweden',
 'Japan',
 'Guatemala',
 'Finland',
 'Yugoslavia',
 'Belgium',
 'United Kingdom',
 'Colombia',
 'Ireland',
 'Australia',
 'Italy']

In [15]:
## all countries from 2015-2017
tot_countries = list(other.Country.unique())
tot_countries

['Federal Democratic Republic of Ethiopia',
 'Republic of Kenya',
 'United States of America',
 'Ukraine',
 'Russian Federation',
 'Italian Republic',
 'Japan',
 'Canada',
 'Kingdom of Belgium',
 'New Zealand',
 'Republic of Belarus',
 'Commonwealth of Australia',
 'United Kingdom of Great Britain and Northern Ireland',
 'Republic of Croatia',
 'Republic of Ecuador',
 'Federal Republic of Germany',
 'Kingdom of Spain',
 'Kingdom of Sweden',
 'Federative Republic of Brazil',
 'Hong Kong SAR',
 'United Mexican States',
 'Kingdom of Denmark',
 'Malaysia',
 'Ireland',
 'Republic of Iceland',
 "People's Republic of China",
 'Republic of Guatemala',
 'Republic of Finland',
 'Slovak Republic',
 'Republic of Colombia',
 'Swiss Confederation',
 'Republic of Austria',
 'Kingdom of the Netherlands',
 'French Republic',
 'Republic of Costa Rica',
 'Republic of Cyprus',
 'Republic of Poland',
 'Kingdom of Norway',
 'Republic of Korea',
 'Portuguese Republic',
 'Republic of China',
 'Republic of Peru',
 'Republic of Singapore',
 'Republic of Panama',
 'Bolivarian Republic of Venezuela',
 'Grand Duchy of Luxembourg',
 'Czech Republic',
 'Socialist Republic of Vietnam',
 'Kingdom of Morocco',
 'Bermuda',
 'Romania',
 'Republic of India',
 'Principality of Liechtenstein',
 'Argentine Republic',
 'Republic of El Salvador',
 'Dominican Republic',
 'State of Israel',
 'Greenland',
 'Republic of Slovenia',
 'Republic of Lithuania',
 'Oriental Republic of Uruguay',
 'Cayman Islands',
 'Republic of Estonia',
 'Jamaica',
 'United Arab Emirates',
 'British Virgin Islands',
 'Republic of TÃ¼rkiye',
 'Republic of Latvia',
 'Principality of Andorra',
 'Sultanate of Oman',
 'Commonwealth of the Bahamas',
 'Republic of Trinidad and Tobago',
 'Republic of Indonesia',
 'Country of CuraÃ§ao',
 'Republic of the Philippines',
 'Republic of Uganda',
 'State of Qatar',
 'Republic of Zimbabwe',
 'Republic of Honduras',
 'Falkland Islands (Malvinas)',
 'Republic of Hungary',
 'Hashemite Kingdom of Jordan',
 'Republic of Albania',
 'Republic of Serbia',
 'Islamic Republic of Pakistan',
 'Nation of Brunei, Abode of Peace',
 'Republic of Burundi',
 'Arab Republic of Egypt',
 'Kingdom of Thailand',
 'Republic of Malta',
 'Kingdom of Saudi Arabia',
 'Republic of San Marino',
 'Republic of Bulgaria',
 "People's Democratic Republic of Algeria",
 'Republic of Nicaragua',
 'Barbados',
 'Republic of Paraguay',
 'Turks and Caicos Islands',
 'State of Kuwait',
 'Mongolia',
 'Federal Republic of Nigeria']

In [16]:
## going back to other['Country'] to match names to the winning countries 
# editing countries list
renamed_countries = []
for country in countries:
    if country=='United States of America':
        temp_c = 'United States'
    elif country=='Federal Republic of Germany':
        temp_c = 'Germany'
    elif country=='Kingdom of Norway':
        temp_c = 'Norway'
    elif country=='Portuguese Republic':
        temp_c = 'Portugal'
    elif country=='Republic of Poland':
        temp_c = 'Poland'
    elif country=='Russian Federation':
        temp_c = 'Russia'
    elif country=='Federal Democratic Republic of Ethiopia':
        temp_c = 'Ethiopia'
    elif country=='Republic of Kenya':
        temp_c = 'Kenya'
    elif country=='Republic of Korea':
        temp_c = 'South Korea'
    elif country=='Kingdom of Sweden':
        temp_c = 'Sweden'
    elif country=='Republic of Guatemala':
        temp_c = 'Guatemala'
    elif country=='Republic of Finland':
        temp_c = 'Finland'
    elif country=='Kingdom of Belgium':
        temp_c = 'Belgium'
    elif country=='United Kingdom of Great Britain and Northern Ireland':
        temp_c = 'United Kingdom'
    elif country=='Republic of Colombia':
        temp_c = 'Colombia'
    elif country=='Commonwealth of Australia':
        temp_c = 'Australia'
    elif country=='Italian Republic':
        temp_c = 'Italy'
    else:
        temp_c = country
    renamed_countries.append(temp_c)
    
other['Country'] = renamed_countries
other

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Year,Unnamed: 8
0,0.0,3,"Desisa, Lelisa",25,M,Ambo,NaN,Ethiopia,NaN,NaN,...,1:47:59,2:02:39,0:04:56,-,2:09:17,1,1,1,2015,NaN
1,1.0,4,"Tsegay, Yemane Adhane",30,M,Addis Ababa,NaN,Ethiopia,NaN,NaN,...,1:47:59,2:02:42,0:04:58,-,2:09:48,2,2,2,2015,NaN
2,2.0,8,"Chebet, Wilson",29,M,Marakwet,NaN,Kenya,NaN,NaN,...,1:47:59,2:03:01,0:04:59,-,2:10:22,3,3,3,2015,NaN
3,3.0,11,"Kipyego, Bernard",28,M,Eldoret,NaN,Kenya,NaN,NaN,...,1:48:03,2:03:47,0:05:00,-,2:10:47,4,4,4,2015,NaN
4,4.0,10,"Korir, Wesley",32,M,Kitale,NaN,Kenya,NaN,NaN,...,1:47:59,2:03:27,0:05:00,-,2:10:49,5,5,5,2015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26405,26405.0,25166,"Steinbach, Paula Eyvonne",61,F,Ontario,CA,United States,NaN,MI,...,5:55:18,6:46:57,0:16:24,-,7:09:39,26407,11972,344,2017,NaN
26406,26406.0,25178,"Avelino, Andrew R.",25,M,Fayetteville,NC,United States,NaN,MI,...,5:53:48,6:54:21,0:16:40,-,7:16:59,26408,14436,4774,2017,NaN
26407,26407.0,27086,"Hantel, Johanna",57,F,Malvern,PA,United States,NaN,NaN,...,6:00:33,6:54:38,0:16:47,-,7:19:37,26409,11973,698,2017,NaN
26408,26408.0,25268,"Reilly, Bill",64,M,New York,NY,United States,NaN,MI,...,6:06:07,6:56:08,0:16:49,-,7:20:44,26410,14437,1043,2017,NaN
26409,26409.0,25266,"Rigsby, Scott",48,M,Alpharetta,GA,United States,NaN,MI,...,6:39:07,7:41:23,0:18:15,-,7:58:14,26411,14438,2553,2017,NaN

In [17]:
## i also do not want to use all 80k rows, so for a random sample:
sample_other = other.sample(n=1000)
sample_other

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Year,Unnamed: 8
2977,2977.0,4797,"Donovan, Evan",24,M,South Portland,ME,United States,NaN,NaN,...,2:37:13,3:01:15,0:07:17,-,3:10:55,2978,2696,1755,2017,NaN
15983,NaN,13051,"Githens, Peter C.",50,M,Reading,PA,United States,NaN,NaN,...,3:12:44,3:43:41,0:09:03,3:56:58,3:56:58,15983,9880,1391,2016,NaN
12992,12992.0,15461,"Muchnick, Steven",60,M,Ellicott City,MD,United States,NaN,NaN,...,3:08:32,3:37:54,0:08:49,-,3:50:54,12994,8573,241,2017,NaN
2048,2048.0,736,"Schenkel, Keith M",24,M,Cincinnati,OH,United States,NaN,NaN,...,2:29:16,2:54:38,0:07:04,-,3:05:07,2049,1900,1347,2017,NaN
18485,NaN,15193,"Burke, Christine",41,F,New York,NY,United States,NaN,NaN,...,3:13:01,3:51:58,0:09:29,4:08:19,4:08:19,18485,7596,1367,2016,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5539,5539.0,10235,"Hillier, Robert D Jr.",49,M,Saginaw,MI,United States,NaN,NaN,...,2:47:45,3:13:12,0:07:48,-,3:24:10,5540,4636,754,2017,NaN
23153,23153.0,26830,"Flynn, Christina",48,F,Salisbury,MA,United States,NaN,NaN,...,3:59:16,4:34:27,0:11:05,-,4:50:13,23155,10173,1647,2017,NaN
20593,20593.0,10451,"Sim, John",46,M,Goleta,CA,United States,NaN,NaN,...,3:38:40,4:12:43,0:10:12,-,4:27:05,20595,11821,2219,2017,NaN
11476,NaN,1998,"Hernandez Garcia, Alberto",36,M,Madrid,NaN,Kingdom of Spain,NaN,NaN,...,2:59:59,3:30:28,0:08:29,3:42:03,3:42:03,11476,7976,3362,2016,NaN
18200,18200.0,21842,"Thiboutot, Denis",56,M,Quebec,QC,Canada,NaN,NaN,...,3:13:17,3:44:01,0:09:03,-,3:56:55,18201,11010,1057,2015,NaN

In [18]:
## putting everything together
df = pd.concat([winners,sample_other])
df

## getting only rows that are necessary
del df['index']
del df['Time']
del df['Distance (Miles)']
del df['Distance (KM)']
del df['Unnamed: 0']
del df['30K']
del df['35K']
del df['40K']
del df['Pace']
del df['Proj Time']
del df['Official Time']
del df['5K']
del df['10K']
del df['15K']
del df['20K']
del df['Half']
del df['25K']
del df['Overall']
del df['Division']
del df['Bib']
del df['City']
del df['State']
del df['Citizen']
del df['Unnamed: 9']
del df['Unnamed: 8']
del df['Age']
del df['Gender']
del df['M/F']

In [19]:
## merge Winner and Name

# under Winner
win = df[:180]
names = []
for w in win.Winner:
    names.append(w)
names

# under Name
nam = df[180:]
names2 = []
for n in nam.Name:
    names2.append(n)
names2

# combine
names_list = names + names2
len(names_list)

1180

In [20]:
del df['Winner']

df['Name'] = names_list
df

         Year           Country                       Name
0      1966.0     United States                 Bobbi Gibb
1      1967.0     United States                 Bobbi Gibb
2      1968.0     United States                 Bobbi Gibb
3      1969.0     United States            Sara Mae Berman
4      1970.0     United States            Sara Mae Berman
...       ...               ...                        ...
5539   2017.0     United States      Hillier, Robert D Jr.
23153  2017.0     United States           Flynn, Christina
20593  2017.0     United States                  Sim, John
11476  2016.0  Kingdom of Spain  Hernandez Garcia, Alberto
18200  2015.0            Canada           Thiboutot, Denis

[1180 rows x 3 columns]

In [21]:
ones = []
for n in range (0,180):
    n = 1
    ones.append(n)
    
zeroes = []
for n in range (0,1000):
    n = 0
    zeroes.append(n)

## adding winners back
winners_bool = ones+zeroes
df['Win?'] = winners_bool
df

         Year           Country                       Name  Win?
0      1966.0     United States                 Bobbi Gibb     1
1      1967.0     United States                 Bobbi Gibb     1
2      1968.0     United States                 Bobbi Gibb     1
3      1969.0     United States            Sara Mae Berman     1
4      1970.0     United States            Sara Mae Berman     1
...       ...               ...                        ...   ...
5539   2017.0     United States      Hillier, Robert D Jr.     0
23153  2017.0     United States           Flynn, Christina     0
20593  2017.0     United States                  Sim, John     0
11476  2016.0  Kingdom of Spain  Hernandez Garcia, Alberto     0
18200  2015.0            Canada           Thiboutot, Denis     0

[1180 rows x 4 columns]

In [24]:
year_str = []
for y in df['Year']:
    year_str.append(str(y))
year_str

df['Year'] = year_str
df

         Year           Country                       Name  Win?
0      1966.0     United States                 Bobbi Gibb     1
1      1967.0     United States                 Bobbi Gibb     1
2      1968.0     United States                 Bobbi Gibb     1
3      1969.0     United States            Sara Mae Berman     1
4      1970.0     United States            Sara Mae Berman     1
...       ...               ...                        ...   ...
5539   2017.0     United States      Hillier, Robert D Jr.     0
23153  2017.0     United States           Flynn, Christina     0
20593  2017.0     United States                  Sim, John     0
11476  2016.0  Kingdom of Spain  Hernandez Garcia, Alberto     0
18200  2015.0            Canada           Thiboutot, Denis     0

[1180 rows x 4 columns]

In [25]:
## done
#df.to_csv('ds210_dataset.csv')